name: Build

on: 
    workflow_dispatch:

    push:
        branches: ['main']

    pull_request:
        branches: ['main']
        types: [opened, synchronize, reopened, ready_for_review]


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: installs dependencies
              run: npm i

            - name: try to build
              run: npm run build